#!/bin/sh

set -e +o pipefail

numprocs='1'
concurrency=''
queue=''

if [ $# != 0 ];
then
  while getopts "c:p:q:" o
  do
    case "$o" in
      "c")
        concurrency="-c $OPTARG"
        ;;
      "p")
        numprocs="$OPTARG"
        ;;
      "q")
        queue="--queue $OPTARG"
        ;;
    esac
  done
fi

echo "
[supervisord]
pidfile=/tmp/supervisord.pid
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:worker]
command=/codecov worker -n %(process_num)d $concurrency $queue
process_name=%(program_name)s_%(process_num)d
autorestart=true
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
numprocs=$numprocs
priority=2
environment=DOCKER='true'
stopwaitsecs=600
" > /supervisord.conf

/usr/bin/supervisord -c /supervisord.conf
