#!/bin/sh

set -e +o pipefail

use_nginx=0
concurrency='-c 1'
numprocs='1'
queue=''
frontends='server localhost:8880;'

if [ $# != 0 ];
then
  while getopts "np:c:q:" o
  do
    case "$o" in
      "n")
        use_nginx=1
        ;;
      "p")
        numprocs="$OPTARG"
        i="0"
        while [ $i -lt $(expr $numprocs - 1) ]
        do
          i=$[$i+1]
          frontends="$frontends
server localhost:888$i;"
        done
        ;;
      "c")
         concurrency="-c $OPTARG"
         ;;
      "q")
         queue="--queue $OPTARG"
         ;;
    esac
  done
fi


if [ -f /nginx.conf ];
then
  # custom nginx provided
  sed -e "s/__FRONTENDS__/$frontends/" /nginx.conf > /.nginx.conf
else
  if [ -f /codecov.crt ] && [ -f /codecov.key ];
  then
    https=",FORCE_HTTPS='true'"
    sed -e "s/__FRONTENDS__/$frontends/" /https.nginx.conf > /.nginx.conf
  else
    https=""
    sed -e "s/__FRONTENDS__/$frontends/" /http.nginx.conf > /.nginx.conf
  fi
fi


echo "
[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
user=root
pidfile=/tmp/supervisord.pid
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:web]
command=/codecov web -p 888%(process_num)d
process_name=%(program_name)s_%(process_num)d
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
numprocs=$numprocs
priority=1
environment=DOCKER='true'$https

[program:worker]
command=/codecov worker -n %(process_num)d $concurrency $queue
process_name=%(program_name)s_%(process_num)d
autorestart=true
startsecs=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
numprocs=1
priority=2
environment=DOCKER='true'
" > /supervisord.conf

if [ $use_nginx = 1 ];
then
  echo "
[program:nginx]
command=sh -c 'sleep 10 && exec nginx -p . -c /.nginx.conf'
process_name=%(program_name)s_%(process_num)d
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
numprocs=1
priority=3
" >> /supervisord.conf

fi

# run supervisor
/usr/bin/supervisord -c /supervisord.conf
